### ISSUE TITLE
Support for Omnipod DASH

### ISSUE THREAD

**Issue by oholsen** [LoopKit/LoopKit#331]
The Omnipod DASH insulin pump as Bluetooth built in. It is appealing to "close the loop" with e.g. a Dexcom G6, Smartphone, and an Omnipod DASH, removing the need for the Rileylink for older Omnipod pumps.

Are there any plans to support the Omnipod DASH insulin pump?

**Comment by ps2** [comment]
Tidepool is working on integrating recent Omnipod pods with their version of Loop, called Tidepool Loop. https://www.tidepool.org/loop/

**Comment by mkdexter** [comment]
It has been a year since this question was asksed.  By now Tidepool I'm sure has arelady written to the code for communicating to Dash, especially since Dash is confirmed an ACE status for Tidepool pumps.  Can't someone who wrote the Tidepool code for Dash bluetooth share it here for the DIY Loop community??

**Comment by ps2** [comment]
Tidepool uses a proprietary manufacturer provided SDK to talk to pods, which is not available for DIY. However, some individuals (not me) in the community have reverse engineered the protocol and have developed an integration that runs on iOS. It is in the final stages of testing for an upcoming release of DIY Loop.

**Comment by mkdexter** [comment]
Thank you.  I stopped using Dash because I like Loop so much better.. Good to know I can find a use for my extra pods in the future.  Thank you Pete.

**Comment by snics** [comment]
> Tidepool uses a proprietary manufacturer provided SDK to talk to pods, which is not available for DIY. However, some individuals (not me) in the community have reverse engineered the protocol and have developed an integration that runs on iOS. It is in the final stages of testing for an upcoming release of DIY Loop. 

@ps2 when is the release for the OmniPod Dash support?

**Comment by Kdisimone** [comment]
@snics when it’s ready. Read the info about testing. No timelines on testing. When it’s ready, it will be released.

**Comment by snics** [comment]
@Kdisimone thanks for the info! Do you have for me then commit or branch? I wanted to take a look at it and merge it into my fork if possible.

**Comment by marionbarker** [comment]
Please search in LoopDocs.

**Comment by snics** [comment]
I've been using the dev branch with the Omnipod DASH for a while now and it works great. Really great work!!

**Comment by vins1243** [comment]
> I've been using the dev branch with the Omnipod DASH for a while now and it works great. Really great work!!

could you tell me how did you install it?

**Comment by snics** [comment]
> could you tell me how did you install it?

Hey, sure I would recommend you to take this: https://github.com/LoopKit/LoopWorkspace

Then you have to check out the dev branch after that, it's like a loop repository. But please be careful the dev branch is called so because it is under development and therefore can have bugs. It is very stable and I have been using it for a long time, but it should be said.
