### ISSUE TITLE
Support for adding new insulin events

### ISSUE THREAD

**Issue by caitp** [LoopKit/LoopKit#376]
I just got back from hospital after accidentally dosing myself with a syringe of insulin meant to fill a new omnipod (long story, don't try to have conversations while filling pod), so after 15 hours and a bunch of dextrose pushes, i I'm in DKA territory, and had a bolus before discharge. I'd like to have that bolus as an event, so that i can avoid overcorrecting with high basal doses. (I am using max basal rates to mitigate this a bit, but adding events manually may be better)

**Comment by marionbarker** [comment]
Please add dose to Apple Health insulin record and run Open Loop until things settle down. 

This page needs an update, but including the link. Scroll to bottom of Insulin record and tap add data. 

https://loopkit.github.io/loopdocs/operation/features/healthapp/

Sorry for your troubles. This is not an “Issue” in the sense that there is a code problem. It’s a request for help - in future see this link. 

https://loopkit.github.io/loopdocs/#stay-in-the-loop

Please close this issue. 


- M

On Oct 27, 2021, at 9:16 AM, ⭐caitp⭐ ***@***.***> wrote:

﻿
I just got back from hospital after accidentally dosing myself with a syringe of insulin meant to fill a new omnipod (long story, don't try to have conversations while filling pod), so after 15 hours and a bunch of dextrose pushes, i I'm in DKA territory, and had a bolus before discharge. I'd like to have that bolus as an event, so that i can avoid overcorrecting with high basal doses. (I am using max basal rates to mitigate this a bit, but adding events manually may be better)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caitp** [comment]
> Sorry for your troubles. This is not an “Issue” in the sense that there is a code problem. It’s a request for help - in future see this link

I would say this is a UX issue

**Comment by marionbarker** [comment]
It’s already added in dev so it will be in the next version of Loop. I have not added this to this page (https://loopkit.github.io/loopdocs/faqs/dev-menus/), so including here. 





- M

On Oct 27, 2021, at 11:15 AM, ⭐caitp⭐ ***@***.***> wrote:

﻿
Sorry for your troubles. This is not an “Issue” in the sense that there is a code problem. It’s a request for help - in future see this link

I would say this is a UX issue

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
