### ISSUE TITLE
Glucose data is removed from Healthkit when it doesn't have to

### ISSUE THREAD

**Issue by beached** [LoopKit/LoopKit#87]
The medtronic cgm users Healthkit glucose data is purged if older than 3hrs on every store of a glucose value.  On Dex this was wanted to prevent duplicate data.  

I have commented it out and I am testing on a medtronic only system right now, but I would like to see at the very least the data left there for Medtronic CGM's.

**Comment by CrushingT1D** [comment]
I see no reason to delete old BG values that Loop has written to healthkit. Current versions of iOS allow for settings in HealthKit where users can determine the priority they'd like to have their data used and does deduping based upon that.

This issue will also make it so that users are not required to turn on Health integration inside their Dexcom app.

**Comment by beached** [comment]
I have a PR ready to go

**Comment by apabari** [comment]
I haven't been able to figure out how to add this functionality to my loop app.  Wondering, will this PR / functionality be added to the main branch of loop?

**Comment by CrushingT1D** [comment]
Try looking in CarbKit in LoopKit

**Comment by beached** [comment]
My fork of loopkit has the one line commented out that prevents removal.  It works now but @ps2 had a better way if i remember

**Comment by CrushingT1D** [comment]
Any update on this one @beached @ps2 ?

**Comment by ps2** [comment]
In loop, you can set `glucoseStore.managedDataInterval = nil` and your data will not be purged.

**Comment by iMaces** [comment]
Still having issues making this work.
Is it just copy/paste the code above or is there some extra work needed?
